In [5]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Arun", "Priya", "Karthik", "Meena", "Rahul"],
    "Department": ["CSE", "IT", "CSE", "ECE", "IT"],
    "Attendance": [82, 91, 76, 68, 88],
    "Python": [85, 92, 76, 65, 88],
    "SQL": [78, 88, 82, 70, 91],
    "Excel": [90, 95, 80, 72, 86]
}
table = pd.DataFrame(data)
print(data)

print(table)

print("First 2 Rows:\n",table.head(2))
print("Last 2 Rows:\n",table.tail(2))

print("Random 3 Rows:\n",table.sample(2))

print("No Of (Rows,Column): ",table.shape)

print("Header:\n",table.columns)

print("Info:\n",table.info())

table.describe()

{'Student_ID': [101, 102, 103, 104, 105], 'Name': ['Arun', 'Priya', 'Karthik', 'Meena', 'Rahul'], 'Department': ['CSE', 'IT', 'CSE', 'ECE', 'IT'], 'Attendance': [82, 91, 76, 68, 88], 'Python': [85, 92, 76, 65, 88], 'SQL': [78, 88, 82, 70, 91], 'Excel': [90, 95, 80, 72, 86]}
   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
4         105    Rahul         IT          88      88   91     86
First 2 Rows:
    Student_ID   Name Department  Attendance  Python  SQL  Excel
0         101   Arun        CSE          82      85   78     90
1         102  Priya         IT          91      92   88     95
Last 2 Rows:
    Student_ID   Name Department  Attendance  Python  SQL  Excel
3         104  Meena        ECE          68      65   70     72
4         105  Rahul         IT          88      88   91     86
Random 3 Rows:
    Student_ID   Name Department  Attendance  Python  SQL  Excel
0         101   Arun        CSE          82      85   78     90
3         104  Meena        ECE          68      65   70     72
No Of (Rows,Column):  (5, 7)
Header:
 Index(['Student_ID', 'Name', 'Department', 'Attendance', 'Python', 'SQL',
       'Excel'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      object
 2   Department  5 non-null      object
 3   Attendance  5 non-null      int64
 4   Python      5 non-null      int64
 5   SQL         5 non-null      int64
 6   Excel       5 non-null      int64
dtypes: int64(5), object(2)
memory usage: 412.0+ bytes
Info:
 None

       Student_ID  Attendance     Python        SQL      Excel
count    5.000000    5.000000   5.000000   5.000000   5.000000
mean   103.000000   81.000000  81.200000  81.800000  84.600000
std      1.581139    9.273618  10.802777   8.318654   8.933085
min    101.000000   68.000000  65.000000  70.000000  72.000000
25%    102.000000   76.000000  76.000000  78.000000  80.000000
50%    103.000000   82.000000  85.000000  82.000000  86.000000
75%    104.000000   88.000000  88.000000  88.000000  90.000000
max    105.000000   91.000000  92.000000  91.000000  95.000000

In [7]:
table[["Student_ID","Attendance","Python","SQL","Excel"]]

   Student_ID  Attendance  Python  SQL  Excel
0         101          82      85   78     90
1         102          91      92   88     95
2         103          76      76   82     80
3         104          68      65   70     72
4         105          88      88   91     86

In [19]:
print(table.iloc[[0,1,2,3]])
dt = table[["Name","Department","Attendance"]]
print(dt)
# Slicing
print(dt[0:4])

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
3         104    Meena        ECE          68      65   70     72
      Name Department  Attendance
0     Arun        CSE          82
1    Priya         IT          91
2  Karthik        CSE          76
3    Meena        ECE          68
4    Rahul         IT          88
      Name Department  Attendance
0     Arun        CSE          82
1    Priya         IT          91
2  Karthik        CSE          76
3    Meena        ECE          68

In [ ]:
k = (table["Attendance"] >= 75)

print(table[k])

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
4         105    Rahul         IT          88      88   91     86

In [29]:
h = (table["Attendance"] >= 75) | (table["Python"] >= 80)

print(table[h])

   Student_ID     Name Department  Attendance  Python  SQL  Excel
0         101     Arun        CSE          82      85   78     90
1         102    Priya         IT          91      92   88     95
2         103  Karthik        CSE          76      76   82     80
4         105    Rahul         IT          88      88   91     86

In [ ]:
mean = table[["Python","SQL","Excel"]].mean()
median = table[["Python","SQL","Excel"]].median()
mode = table[["Python","SQL","Excel"]].mode()

print(mean)
print(median)
print(mode)

Python    81.2
SQL       81.8
Excel     84.6
dtype: float64
Python    85.0
SQL       82.0
Excel     86.0
dtype: float64
   Python  SQL  Excel
0      65   70     72
1      76   78     80
2      85   82     86
3      88   88     90
4      92   91     95